[phases.setup]
nixPkgs = ["nodejs", "pnpm", "python3", "gcc", "gnumake", "glibc.dev"]

[phases.install]
cmds = [
    "pnpm install --frozen-lockfile",
    "pnpm rebuild"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"