[phases.setup]
nixPkgs = ["nodejs", "pnpm", "python3", "gcc", "gnumake", "glibc.dev"]
nixLibs = ["gcc-unwrapped"]
aptPkgs = ["build-essential"]

[phases.install]
cmds = [
    "pnpm install --frozen-lockfile",
    "cd node_modules/node-pty && npm run install",
    "cd ../.. && pnpm rebuild better-sqlite3"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"